### ISSUE TITLE
Driver programm example

### ISSUE THREAD

**Issue by stgleb** [xiang90/paxos#1]
Hello, could you write please driver program example for your paxos package?

**Comment by xiang90** [comment]
@stgleb What do you plan to do with this paxos pkg?

**Comment by stgleb** [comment]
Maybe not package, but at list driver program with main that shows basic usage of package. May purpose is studying.

**Comment by xiang90** [comment]
@stgleb Yea... This paxos is just built for studying purpose. So it will only contain the core algo, and nothing else. I will probably not write any example myself. Feel free to send pull requests if you want. Thanks!
